# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
            node-version: '10.x'

      # Installs node and creates a prod build in the system
      - name: Started to build the project
        run: |
          echo Installing Npm
          npm install
          echo Installation completed for npm
          echo Starting the build
          npm build --prod
          echo Build completed
      # Uploading the file to s3
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'dist/senba'
          destination_dir: 'senba.zip'
      # upload the file into artifacts
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
              #  Artifact name
            #name: # optional, default is artifact
            # A file, directory or wildcard pattern that describes what to upload
            path: 'dist'
